### ISSUE TITLE
Create Graph Layout

### ISSUE THREAD

**Issue by AthulKrishna14310** [AthulKrishna14310/CharachterAnalyser#11]
**Layout blueprint**

![20210413_151917.jpg](https://user-images.githubusercontent.com/37478917/114533697-cd04a700-9c6b-11eb-8505-edf37d8420b8.jpg)

**Tasks**
- [x] Create layout in activity_mail.xml
- [x] Show graph for score
- [x] Show graph for time
- [x] Show graph for No: of errors
- [x] Show graph for speed

**Constraints**

- Refresh all data while choosing letter and score
- X axis attempts in ascending order
- List View attempts in descending order

**Tutorial**

- https://material.io/components/menus#exposed-dropdown-menu
- https://material.io/components/lists
- https://github.com/jjoe64/GraphView/wiki/Line-Graph
- https://github.com/jjoe64/GraphView/wiki/Static-labels

**Reference**
<?xml version="1.0" encoding="utf-8"?>
```
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.example.letterpractice.DrawView
        android:id="@+id/draw_view"
        android:layout_width="600dp"
        android:layout_height="400dp"
        android:layout_alignParentRight="true"
        android:layout_marginTop="16dp"
        android:layout_marginRight="16dp"
        android:layout_centerVertical="true"
         />

    <com.google.android.material.button.MaterialButton

        android:id="@+id/submitButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:drawableTop="@drawable/ic_baseline_check_24"
        android:text="Submit"
        android:padding="16dp"
        style="@style/Widget.MaterialComponents.Button.UnelevatedButton"
        android:layout_margin="16dp"
        />

    <com.google.android.material.button.MaterialButton

        android:id="@+id/homeButton"
        style="@style/Widget.MaterialComponents.Button.OutlinedButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentLeft="true"
        android:layout_alignParentBottom="true"
        android:layout_marginStart="16dp"
        android:layout_marginLeft="16dp"
        android:layout_marginTop="16dp"
        android:layout_marginEnd="16dp"
        android:layout_marginBottom="16dp"
        android:drawableTop="@drawable/ic_home_black_24dp"
        android:padding="16dp"
        android:text="  Home  "
        />
    <com.google.android.material.button.MaterialButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_margin="16dp"
        android:text="Choose your letter from below"
        style="@style/Widget.MaterialComponents.Button.TextButton"
        app:cornerRadius="6dp"
        android:padding="16dp"
        android:id="@+id/selector"
        />
    <com.google.android.material.button.MaterialButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_margin="16dp"
        android:drawableTint="@color/colorPrimary"
        android:drawableLeft="@drawable/ic_outline_info_24"
        android:text="Instructions"
        style="@style/Widget.MaterialComponents.Button.OutlinedButton"
        android:tint="@color/colorPrimary"
        android:padding="16dp"
        android:id="@+id/instruction"
        />

    <com.google.android.material.button.MaterialButton

        android:id="@+id/refreshButton"
        style="@style/Widget.MaterialComponents.Button.OutlinedButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_marginStart="16dp"
        android:layout_marginLeft="16dp"
        android:layout_marginTop="16dp"
        android:layout_marginEnd="16dp"
        android:layout_marginBottom="16dp"
        android:layout_toRightOf="@id/homeButton"
        android:drawableTop="@drawable/ic_refresh_black_24dp"

        android:padding="16dp"
        android:text="Refresh"
        />
    <com.google.android.material.chip.ChipGroup
        android:id="@+id/chipGroup"
        android:layout_width="match_parent"
        android:layout_marginTop="16dp"
        android:layout_marginLeft="16dp"
        android:layout_centerVertical="true"
        app:singleSelection="true"
        app:chipSpacingHorizontal="8dp"
        app:chipSpacingVertical="8dp"
        android:layout_toLeftOf="@id/draw_view"
        android:layout_height="wrap_content">
        <com.google.android.material.chip.Chip
            android:id="@+id/chipA"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            

            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="A a"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipB"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="B b"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipC"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="C c"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipD"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="D d"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipE"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="E e"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipF"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="F f"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipG"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="G g"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipH"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="H h"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipI"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="I i"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipJ"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
            
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="J j"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipK"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
            
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="K k"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipL"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="L l"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipM"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="M m"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipN"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="N n"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipO"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="O o"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipP"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="P p"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipQ"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="Q q"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipR"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="R r"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipS"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="S s"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipT"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="T t"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipU"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="U u"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipV"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="V v"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipW"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="W w"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipY"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="X x"

            android:checkable="true"
            />
        <com.google.android.material.chip.Chip
            android:id="@+id/chipZ"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:chipMinHeight="48dp"
            app:chipCornerRadius="8dp"
            app:iconEndPadding="8dp"
                app:iconStartPadding="8dp" android:layout_margin="8dp"
            
            app:chipStrokeColor="@color/colorPrimary"
            app:chipBackgroundColor="#FFFF"
            app:chipStrokeWidth="1dp"
            android:textColor="@color/colorPrimaryDark"
            android:textAppearance="@style/TextAppearance.MaterialComponents.Headline5"
            app:checkedIcon="@drawable/ic_baseline_check_circle_24"
            android:text="Y y"

            android:checkable="true"
            />


    </com.google.android.material.chip.ChipGroup>
</RelativeLayout>
```

**Pending**

- Animation
